ServerName localhost

<VirtualHost *:80>
    # InjectedServerAlias

    DocumentRoot /var/www/baikal/html

    RewriteEngine On
    RewriteRule ^/\.well-known/carddav$ /dav.php [R=308,L]
    RewriteRule ^/\.well-known/caldav$ /dav.php [R=308,L]

    <Directory /var/www/baikal/html>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/baikal-error.log
    CustomLog ${APACHE_LOG_DIR}/baikal-access.log combined
</VirtualHost>
